[package]
name = "request-interface"
version = "0.1.0"
authors = ["Jameson Hodge <contact@jamesonhodge.com>"]
edition = "2018"

[dependencies]
near-sdk = { git = "https://github.com/near/near-sdk-rs.git", rev="249dacdcd3fd34bc00f0895a275f33f05cd910c1" }
oracle = { path = "./../oracle" }
serde = "1.0.118"
